### ISSUE TITLE
Port poetry

### ISSUE THREAD

**Issue by scarrazza** [qiboteam/qibojit#111]

**Comment by AleCandido** [comment]
@Edoardo-Pedicillo if you can, start doing the same that you did for Qibo:

- [ ] `poetry init` and define the projects metadata (porting them from `setup.py`)
- [ ] add dependencies as we have done together
	- hopefully will be much simpler
	- remember that the Python versions range we are targeting is [3.8, 3.11] (extremes included)
- [ ] upgrade workflows to use Poetry ones

**Comment by stavros11** [comment]
@scarrazza are we still planning to do this? It is useful if we want to use the selfhosted workflow for qibojit tests, otherwise we need to write a different workflow that is not using poetry. If we move to poetry we should also move `tests` outside `src`, as we did for qibo and qibolab.

**Comment by scarrazza** [comment]
Yes, absolutely, however I am not sure if @Edoardo-Pedicillo had time to look into this yet.
