### ISSUE TITLE
Improvements for cuQuantum backend

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibojit#112]
After having a chat with the guys at NVIDIA-cuQuantum they suggested that in order to increase performances we could try to reduce the number of memory allocations. Currently we have the following mechanims:
https://github.com/qiboteam/qibojit/blob/5a4125a8b1cc7373228e4967f2276c81cc5d00da/src/qibojit/backends/gpu.py#L705-L723 
So, basically everytime that a gate requires extra workspace we allocate it. 
A possible solution that they proposed consists in the following:

- Having a `workspace` member of the class `CuQuantumBackend` initialized at a fixed value (8 MB or 16 MB)
- Keeping track of the workspace during the execution in order to allocate extra memory only if we run out of memory. Somethings like:
```python
if current_workspace + workspace_required > workspace_allocated:
    allocate_memory
```

- They also suggested that during the allocation we should allocate a considerable amount of memory to avoid allocating small bits of memory for each gate.

Other things mentioned during the meeting:

- check if this block of code is needed https://github.com/qiboteam/qibojit/blob/5a4125a8b1cc7373228e4967f2276c81cc5d00da/src/qibojit/backends/gpu.py#L539-L544
- they should now support multi GPU for `cuquantum-python`

@scarrazza @stavros11 let me know what you think.
If you agree I will try to implement the solution that they proposed for handling the workspace.

**Comment by andrea-pasquale** [comment]
I guess that this issue can be closed given that we showed them that the `CuQuantum` implementation is slower compared to `Cupy` because of the custom operators.

**Comment by andrea-pasquale** [comment]
@scarrazza I think that this issue can be closed until we hear something from Nvidia.

**Comment by scarrazza** [comment]
Thanks.
