### ISSUE TITLE
No version `0.0.11` on pypi

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibojit#131]
While preparing some tutorial I've noticed that despite having a release for the `0.0.11` version, this version is not on [pypi](https://pypi.org/project/qibojit/).
@scarrazza for the tutorial I don't think that changing the version will matter that much. However, if we want the students to use the latest version we should put in on pypi.

**Comment by scarrazza** [comment]
Well spotted, thanks. I have restarted the failed job which uploads to pypi: https://github.com/qiboteam/qibojit/actions/runs/5411369726

**Comment by scarrazza** [comment]
Pypi upload checks are failing in https://github.com/qiboteam/qibojit/actions/runs/5411369726/job/15226508567#step:14:24. @AleCandido are we missing the `readme` key?

**Comment by scarrazza** [comment]
To unlock @andrea-pasquale, I have manually uploaded the 0.0.11 to pypi, but indeed, the `long_description` is missing in our pyproject.yaml.

**Comment by AleCandido** [comment]
Yes, that's exactly the `readme` key in Poetry, and it's currently missing in `pyproject.toml`:

https://github.com/qiboteam/qibojit/blob/e90fdf887633aa6d91210a5a6e784a160cf0aa61/pyproject.toml#L1-L13

**Comment by scarrazza** [comment]
@Edoardo-Pedicillo could you please fix this?
