### ISSUE TITLE
Long cupy dry run

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibojit#27]
As discussed in other threads it seems that we have a 0.5sec overhead in cupy's dry run when compared to simulation times. I am opening this issue to post some profiling results related to this and discuss potential solutions. 

I profiled a script that calls only the `inital_state` operator which uses a minimal set of arguments: `state = op.initial_state(nqubits, "complex128")` and does not require any casting or GPU-CPU transfer. The following table shows the corresponding dry run (first call), simulation (second call) and compile times. The compile time is found by looking at the cummulative time spend on cupy's [`_compile_with_cache_cuda`](https://github.com/cupy/cupy/blob/20915f55bbbb99b2a85f662d26414233c18465bf/cupy/cuda/compiler.py#L477) method as logged in the profiling output.

<details>
<summary> Profiling results</summary>

nqubits | dry run | simulation | cupy | dry run - compile - simulation
-- | -- | -- | -- | --
3 | 1.07826 | 0.00002 | 1.077 | 0.00124
4 | 0.75259 | 0.00002 | 0.751 | 0.00157
5 | 0.79743 | 0.00002 | 0.796 | 0.00141
6 | 0.73674 | 0.00002 | 0.735 | 0.00173
7 | 0.98545 | 0.00002 | 0.984 | 0.00143
8 | 0.75880 | 0.00002 | 0.756 | 0.00278
9 | 0.75664 | 0.00002 | 0.755 | 0.00162
10 | 0.70874 | 0.00002 | 0.707 | 0.00172
11 | 0.79865 | 0.00002 | 0.797 | 0.00163
12 | 0.66965 | 0.00002 | 0.668 | 0.00163
13 | 0.67687 | 0.00002 | 0.676 | 0.00085
14 | 0.73576 | 0.00002 | 0.735 | 0.00074
15 | 0.75079 | 0.00002 | 0.749 | 0.00178
16 | 0.73728 | 0.00002 | 0.736 | 0.00126
17 | 1.46634 | 0.00005 | 1.464 | 0.00229
18 | 0.69862 | 0.00002 | 0.697 | 0.00160
19 | 1.39950 | 0.00005 | 1.398 | 0.00145
20 | 0.72016 | 0.00003 | 0.719 | 0.00114
21 | 0.73185 | 0.00003 | 0.731 | 0.00082
22 | 0.71809 | 0.00003 | 0.717 | 0.00106
23 | 0.72895 | 0.00004 | 0.728 | 0.00091
24 | 0.69690 | 0.00411 | 0.695 | -0.00221
25 | 0.69932 | 0.00170 | 0.697 | 0.00062
26 | 0.70868 | 0.00175 | 0.707 | -0.00007
27 | 1.91245 | 0.00025 | 1.907 | 0.00520
28 | 1.29077 | 0.00018 | 1.286 | 0.00459
29 | 0.90459 | 0.00057 | 0.898 | 0.00602
30 | 0.77462 | 0.00292 | 0.761 | 0.01069

</details>

So it seems that the whole dry run overhead comes from this function call. @scarrazza, do you have other examples where cupy compilation is fast?

**Comment by scarrazza** [comment]
@stavros11 thanks, could you please profile again by commenting all kernels that are not used in this example?

**Comment by scarrazza** [comment]
Ok, so cache is working. Could you please measure how long the `initial_state_kernel` compilation takes if you pass 1 vs 25 qubits? (just to check if a light tracing could help here)

**Comment by scarrazza** [comment]
Thanks. Moving to the initialization is probably an interesting suggestion, on the other hand this overhead will disappear as soon as we use GPU for an appropriate system size.

**Comment by mlazzarin** [comment]
I know this is a closed issue, but I just want to add that, if we want to move the compilation to the import step we can simply try to add ``self.gates.compile()`` in the ``__init__()`` method of the ``CupyBackend`` class.
