### ISSUE TITLE
Dry run overhead is inconsistent between different environments

### ISSUE THREAD

**Issue by mlazzarin** [qiboteam/qibojit#44]
I've noticed that the dry run overhead is inconsistent between different environments.
For example, these are the results on the same machine with the same version of qibo and qibojit.
As always, I have disabled the compilation during import time.

 - CuPy 9.6.0, cudatoolkit v12.2.0 both from ``conda-forge``: ~3.9 s, ~ 3.3 s with cached kernels
 - CuPy 9.6.0 from pip (``cupy-cuda115``), system installation of cuda v11.5: ~ 3.7 s, ~ 3.2 s with cached kernels
 - CuPy 9.5.0, cudatoolkit v11.2.2 both from ``conda-forge``: ~2.7 s, ~ 2.3 s with cached kernels
 - CuPy 9.6.0, cudatoolkit v11.1.1 both from ``conda-forge``: ~2.2 s, ~ 1.6 s with cached kernels
 - CuPy 9.5.0, cudatoolkit v11.1.1 both from ``conda-forge``: ~1.4 s, ~ 0.9 s with cached kernels

and so on. Two comments:
 - It seems like the caching system is working, but the effect is limited.
 - We may just leave the compilation during import, but an user with the most updated environment will see ~ 5 s of import time on the machine I'm using. On the other hand, I'm going to open a draft PR soon to discuss a possible way to decrease the compilation times. EDIT (see #45)

**Comment by mlazzarin** [comment]
I prepared a gist with all the requirements to reproduce the problem. https://gist.github.com/mlazzarin/1e2128e90d78c4cb1a220075f64bc297
When I have time I'll collect some numbers from different machines.

Notice that I've just found out that using ``.compile()`` will make CuPy ignore the kernel cache, but this is somehow orthogonal to this issue.

**Comment by mlazzarin** [comment]
I collected some results:

OS: Ubuntu 20.04.3 LTS
CPU: AMD EPYC 7742
GPU: NVIDIA RTX A6000
Driver version: 495.29.05

| Environment                                                                             | Compilation time |
| -------------------------------------------------------------------------------- | ---------------------- |
| System installation of CUDA 11.5, ``cupy-cuda115`` from pip | ~ 3.2 s                 |
| ``cudatoolkit=11.5.0`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.4.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.3.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.2 s                 |
| ``cudatoolkit=11.2.2`` and ``cupy=9.6.0`` from conda-forge    | ~ 3.4 s                 |
| ``cudatoolkit=11.1.1`` and ``cupy=9.6.0`` from conda-forge    | ~ 1.6 s                 |
| ``cudatoolkit=11.5.0`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.4.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.3.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.1 s  (3.2 s first exec) |
| ``cudatoolkit=11.2.2`` and ``cupy=9.5.0`` from conda-forge    | ~ 2.3 s  (3.5 s first exec) |
| ``cudatoolkit=11.1.1`` and ``cupy=9.5.0`` from conda-forge    | ~ 1.0 s  (1.7 s first exec) |

As you can see, we see two different trends:
 - ``cudatoolkit=11.1.1`` is faster than the others.
 - The first execution with ``cupy=9.5.0`` is slower than the following ones, and the compilation time during the first execution is similar to that of ``cupy=9.6.0``.
    With 'first execution' I mean the very first execution in a new conda environment.
    Manually removing ``~/.cupy/kernel_cache`` does nothing (maybe because I'm using the ``.compile()`` method) so it looks like ``cupy=9.5.0`` is using some other kind of caching.

**Comment by scarrazza** [comment]
Thanks for the se numbers. I think you can open an issue in cupy posting this table.

**Comment by mlazzarin** [comment]
Ok, I opened an issue in cupy regarding this (https://github.com/cupy/cupy/issues/6139).

**Comment by mlazzarin** [comment]
Following the discussion in the issue above and in PR #45, I think we can close this issue.
