### ISSUE TITLE
Kernel calls and thread synchronization

### ISSUE THREAD

**Issue by mlazzarin** [qiboteam/qibojit#49]
In ``CupyBackend`` the thread synchronization after kernel calls seems inconsistent.
In particular, it is used in ``one_qubit_base``, ``two_qubit_base`` and ``multi_qubit_base``, but it is not used in ``initial_state`` and ``collapse_state``.

If it is mandatory, we should add it where it's missing, otherwise we should remove it where it's unnecessary. What do you think?

**Comment by scarrazza** [comment]
Yes, I believe we should include the sync everywhere.
