### ISSUE TITLE
Wrong result when applying unitary matrix using cuquantum

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibojit#62]
The following fails:
```Python
import numpy as np
import qibo
from qibo import models, gates
from scipy.linalg import expm
qibo.set_backend("qibojit", platform="cuquantum")

# generate random unitary matrix
matrix = np.random.random((2, 2)) + 1j * np.random.random((2, 2))
matrix = expm(1j * (matrix + matrix.T.conj()))

initial_state = np.random.random(2) + 1j * np.random.random(2)
initial_state = initial_state / np.sqrt(np.sum(np.abs(initial_state) ** 2))
target_state = matrix.dot(initial_state)

circuit = models.Circuit(1)
circuit.add(gates.Unitary(matrix, 0))
final_state = circuit(initial_state=np.copy(initial_state))

np.testing.assert_allclose(final_state, target_state)
```
while if I remove the `expm` line it works.

This issue is captured by `test_cirq.py` in qibo using `QIBOJIT_PLATFORM=cuquantum pytest test_cirq.py`. Interestingly if one uses `QIBOJIT_PLATFORM pytest` to run all the tests the issue does not appear. This means that the platform is switched back to cupy somewhere in the previous tests and cuquantum is not tested properly. This issue will be resolved in qiboteam/qibo#539 so it may be a good idea to wait for this before making any releases.

**Comment by scarrazza** [comment]
I confirm this issue, and if I do:
```python
matrix = expm(1j * (matrix + matrix.T.conj())).flatten().reshape(2,2)
```
the issue disappears. Most likely expm is delivering an array with order `!= C`, while reshape reprojects in `C`.
@stavros11 please try and let me know, an workaround is to cast matrix in `C`.

**Comment by stavros11** [comment]
> I confirm this issue, and if I do:
> 
> ```python
> matrix = expm(1j * (matrix + matrix.T.conj())).flatten().reshape(2,2)
> ```
> 
> the issue disappears. Most likely expm is delivering an array with order `!= C`, while reshape reprojects in `C`. @stavros11 please try and let me know, an workaround is to cast matrix in `C`.

Thank you for finding the fix, it works for me too. Indeed doing `np.array(x, order='C')` works too. Yesterday I was trying with just `np.array` and it wasn't working, I am assuming it stays in the existing order if we don't specify a new one. I guess we could fix this by changing the platform casts to have an order argument. I will open a PR implementing this here.

We could just fix the qibo tests that use `expm` but I believe it is better to implement it here as some user may use it as well.

**Comment by scarrazza** [comment]
@stavros11 thanks, and I agree with the solution.
