### ISSUE TITLE
Cuquantum fails using the latest release

### ISSUE THREAD

**Issue by stavros11** [qiboteam/qibojit#76]
I believe a new cuquantum-python version was uploaded in [conda-forge](https://anaconda.org/conda-forge/cuquantum-python) yesterday and there are some changes in the API. For example our cuquantum tests both in qibo and qibojit now fail with
```
AttributeError: module 'cuquantum.custatevec' has no attribute 'apply_matrix_buffer_size'
```
I believe this method was renamed to [`apply_matrix_get_workspace_size`](https://docs.nvidia.com/cuda/cuquantum/python/api/custatevec.html#general-matrices) in the latest version. I have not checked in detail if any other changes have been made.

**Comment by scarrazza** [comment]
@stavros11 thanks for finding this, @andrea-pasquale could you please have a look?

**Comment by andrea-pasquale** [comment]
Yes, it seems like they renamed that method.
I'll have a look.
