### ISSUE TITLE
Add cuQuantum version in documentation

### ISSUE THREAD

**Issue by andrea-pasquale** [qiboteam/qibojit#78]
Once we merge #77 the cuquantum backend will work only with the latest version of cuquantum which currently is the [22.03.0](https://docs.nvidia.com/cuda/cuquantum/python/release_notes.html#cuquantum-python-v22-03-0).
We should add this to the qibo documentation.

**Comment by scarrazza** [comment]
@andrea-pasquale shall we close this issue?
